const ACTIONS = {
	GET_CATEGORIES_REQ: 'GET_CATEGORIES_REQ',
	GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
	GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

	GET_ARTICLES_REQ: 'GET_ARTICLES_REQ',
	GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',
	GET_ARTICLES_FAILURE: 'GET_ARTICLES_FAILURE',

	GET_ARTICLE_HISTORY_REQ: 'GET_ARTICLE_HISTORY_REQ',
	GET_ARTICLE_HISTORY_SUCCESS: 'GET_ARTICLE_HISTORY_SUCCESS',
	GET_ARTICLE_HISTORY_FAILURE: 'GET_ARTICLE_HISTORY_FAILURE',

	CREATE_CATEGORY_REQ: 'CREATE_CATEGORY_REQ',
	CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
	CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

	CREATE_ARTICLE_REQ: 'CREATE_ARTICLE_REQ',
	CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
	CREATE_ARTICLE_FAILURE: 'CREATE_ARTICLE_FAILURE',

	UPDATE_CATEGORY_REQ: 'UPDATE_CATEGORY_REQ',
	UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
	UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

	UPDATE_ARTICLE_REQ: 'UPDATE_ARTICLE_REQ',
	UPDATE_ARTICLE_SUCCESS: 'UPDATE_ARTICLE_SUCCESS',
	UPDATE_ARTICLE_FAILURE: 'UPDATE_ARTICLE_FAILURE',

	DELETE_CATEGORY_REQ: 'DELETE_CATEGORY_REQ',
	DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
	DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',

	DELETE_ARTICLE_REQ: 'DELETE_ARTICLE_REQ',
	DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
	DELETE_ARTICLE_FAILURE: 'DELETE_ARTICLE_FAILURE',

	VOTE_ARTICLE_REQ: 'VOTE_ARTICLE_REQ',
	VOTE_ARTICLE_SUCCESS: 'VOTE_ARTICLE_SUCCESS',
	VOTE_ARTICLE_FAILURE: 'VOTE_ARTICLE_FAILURE',

	FOLLOW_ARTICLE_REQ: 'FOLLOW_ARTICLE_REQ',
	FOLLOW_ARTICLE_SUCCESS: 'FOLLOW_ARTICLE_SUCCESS',
	FOLLOW_ARTICLE_FAILURE: 'FOLLOW_ARTICLE_FAILURE',

	GET_COMMENTS_REQ: 'GET_COMMENTS_REQ',
	GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
	GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

	NEW_COMMENT_REQ: 'NEW_COMMENT_REQ',
	NEW_COMMENT_SUCCESS: 'NEW_COMMENT_SUCCESS',
	NEW_COMMENT_FAILURE: 'NEW_COMMENT_FAILURE',

	UPDATE_COMMENT_REQ: 'UPDATE_COMMENT_REQ',
	UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS',
	UPDATE_COMMENT_FAILURE: 'UPDATE_COMMENT_FAILURE',

	DELETE_COMMENT_REQ: 'DELETE_COMMENT_REQ',
	DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
	DELETE_COMMENT_FAILURE: 'DELETE_COMMENT_FAILURE',

	RESTORE_ARTICLE_REQ: 'RESTORE_ARTICLE_REQ',
	RESTORE_ARTICLE_SUCCESS: 'RESTORE_ARTICLE_SUCCESS',
	RESTORE_ARTICLE_FAILURE: 'RESTORE_ARTICLE_FAILURE',

	REVERT_ARTICLE_REQ: 'REVERT_ARTICLE_REQ',
	REVERT_ARTICLE_SUCCESS: 'REVERT_ARTICLE_SUCCESS',
	REVERT_ARTICLE_FAILURE: 'REVERT_ARTICLE_FAILURE',
}

export default ACTIONS
