const ACTIONS = {
	EMPLOYEE_MODULES_REQ: 'EMPLOYEE_MODULES_REQ',
	EMPLOYEE_MODULES_SUCCESS: 'EMPLOYEE_MODULES_SUCCESS',
	EMPLOYEE_MODULES_FAILURE: 'EMPLOYEE_MODULES_FAILURE',
}

export default ACTIONS
