const ACTIONS = {
	EMPLOYEE_MODULES_REQ: 'EMPLOYEE_MODULES_REQ',
	EMPLOYEE_MODULES_SUCCESS: 'EMPLOYEE_MODULES_SUCCESS',
	EMPLOYEE_MODULES_FAILURE: 'EMPLOYEE_MODULES_FAILURE',

	LOAD_ALL_EMPLOYEES_REQ: 'LOAD_ALL_EMPLOYEES_REQ',
	LOAD_ALL_EMPLOYEES_SUCCESS: 'LOAD_ALL_EMPLOYEES_SUCCESS',
	LOAD_ALL_EMPLOYEES_FAILURE: 'LOAD_ALL_EMPLOYEES_FAILURE',

	LOAD_ACTIVE_EMPLOYEES_REQ: 'LOAD_ACTIVE_EMPLOYEES_REQ',
	LOAD_ACTIVE_EMPLOYEES_SUCCESS: 'LOAD_ACTIVE_EMPLOYEES_SUCCESS',
	LOAD_ACTIVE_EMPLOYEES_FAILURE: 'LOAD_ACTIVE_EMPLOYEES_FAILURE',

	LOAD_INACTIVE_EMPLOYEES_REQ: 'LOAD_INACTIVE_EMPLOYEES_REQ',
	LOAD_INACTIVE_EMPLOYEES_SUCCESS: 'LOAD_INACTIVE_EMPLOYEES_SUCCESS',
	LOAD_INACTIVE_EMPLOYEES_FAILURE: 'LOAD_INACTIVE_EMPLOYEES_FAILURE',

	LOAD_SUSPENDED_EMPLOYEES_REQ: 'LOAD_SUSPENDED_EMPLOYEES_REQ',
	LOAD_SUSPENDED_EMPLOYEES_SUCCESS: 'LOAD_SUSPENDED_EMPLOYEES_SUCCESS',
	LOAD_SUSPENDED_EMPLOYEES_FAILURE: 'LOAD_SUSPENDED_EMPLOYEES_FAILURE',

	INVITE_EMPLOYEE_REQ: 'INVITE_EMPLOYEE_REQ',
	INVITE_EMPLOYEE_SUCCESS: 'INVITE_EMPLOYEE_SUCCESS',
	INVITE_EMPLOYEE_FAILURE: 'INVITE_EMPLOYEE_FAILURE',

	SET_NEW_EMPLOYEE_DETAILS: 'SET_NEW_EMPLOYEE_DETAILS',

	VALIDATE_TOKEN_REQ: 'VALIDATE_TOKEN_REQ',
	VALIDATE_TOKEN_SUCCESS: 'VALIDATE_TOKEN_SUCCESS',
	VALIDATE_TOKEN_FAILURE: 'VALIDATE_TOKEN_FAILURE',

	REGISTER_EMPLOYEE_REQ: 'REGISTER_EMPLOYEE_REQ',
	REGISTER_EMPLOYEE_SUCCESS: 'REGISTER_EMPLOYEE_SUCCESS',
	REGISTER_EMPLOYEE_FAILURE: 'REGISTER_EMPLOYEE_FAILURE',

	LOAD_SELECTED_EMPLOYEE_REQ: 'LOAD_SELECTED_EMPLOYEE_REQ',
	LOAD_SELECTED_EMPLOYEE_SUCCESS: 'LOAD_SELECTED_EMPLOYEE_SUCCESS',
	LOAD_SELECTED_EMPLOYEE_FAILURE: 'LOAD_SELECTED_EMPLOYEE_FAILURE',
}

export default ACTIONS
