const ACTIONS = {
	LOAD_ALL_PROJECTS_REQ: 'LOAD_ALL_PROJECTS_REQ',
	LOAD_ALL_PROJECTS_SUCCESS: 'LOAD_ALL_PROJECTS_SUCCESS',
	LOAD_ALL_PROJECTS_FAILURE: 'LOAD_ALL_PROJECTS_FAILURE',

	LOAD_INPROGRESS_PROJECTS_REQ: 'LOAD_INPROGRESS_PROJECTS_REQ',
	LOAD_INPROGRESS_PROJECTS_SUCCESS: 'LOAD_INPROGRESS_PROJECTS_SUCCESS',
	LOAD_INPROGRESS_PROJECTS_FAILURE: 'LOAD_INPROGRESS_PROJECTS_FAILURE',

	LOAD_OVERDUE_PROJECTS_REQ: 'LOAD_OVERDUE_PROJECTS_REQ',
	LOAD_OVERDUE_PROJECTS_SUCCESS: 'LOAD_OVERDUE_PROJECTS_SUCCESS',
	LOAD_OVERDUE_PROJECTS_FAILURE: 'LOAD_OVERDUE_PROJECTS_FAILURE',

	LOAD_CLOSED_PROJECTS_REQ: 'LOAD_CLOSED_PROJECTS_REQ',
	LOAD_CLOSED_PROJECTS_SUCCESS: 'LOAD_CLOSED_PROJECTS_SUCCESS',
	LOAD_CLOSED_PROJECTS_FAILURE: 'LOAD_CLOSED_PROJECTS_FAILURE',

	NEW_PROJECT_REQ: 'NEW_PROJECT_REQ',
	NEW_PROJECT_SUCCESS: 'NEW_PROJECT_SUCCESS',
	NEW_PROJECT_FAILURE: 'NEW_PROJECT_FAILURE',

	LOAD_ALL_TASKS_REQ: 'LOAD_ALL_TASKS_REQ',
	LOAD_ALL_TASKS_SUCCESS: 'LOAD_ALL_TASKS_SUCCESS',
	LOAD_ALL_TASKS_FAILURE: 'LOAD_ALL_TASKS_FAILURE',

	LOAD_OPEN_TASKS_REQ: 'LOAD_OPEN_TASKS_REQ',
	LOAD_OPEN_TASKS_SUCCESS: 'LOAD_OPEN_TASKS_SUCCESS',
	LOAD_OPEN_TASKS_FAILURE: 'LOAD_OPEN_TASKS_FAILURE',

	LOAD_INPROGRESS_TASKS_REQ: 'LOAD_INPROGRESS_TASKS_REQ',
	LOAD_INPROGRESS_TASKS_SUCCESS: 'LOAD_INPROGRESS_TASKS_SUCCESS',
	LOAD_INPROGRESS_TASKS_FAILURE: 'LOAD_INPROGRESS_TASKS_FAILURE',

	LOAD_REVIEW_TASKS_REQ: 'LOAD_REVIEW_TASKS_REQ',
	LOAD_REVIEW_TASKS_SUCCESS: 'LOAD_REVIEW_TASKS_SUCCESS',
	LOAD_REVIEW_TASKS_FAILURE: 'LOAD_REVIEW_TASKS_FAILURE',

	LOAD_OVERDUE_TASKS_REQ: 'LOAD_OVERDUE_TASKS_REQ',
	LOAD_OVERDUE_TASKS_SUCCESS: 'LOAD_OVERDUE_TASKS_SUCCESS',
	LOAD_OVERDUE_TASKS_FAILURE: 'LOAD_OVERDUE_TASKS_FAILURE',

	LOAD_CLOSED_TASKS_REQ: 'LOAD_CLOSED_TASKS_REQ',
	LOAD_CLOSED_TASKS_SUCCESS: 'LOAD_CLOSED_TASKS_SUCCESS',
	LOAD_CLOSED_TASKS_FAILURE: 'LOAD_CLOSED_TASKS_FAILURE',

	LOAD_SELECTED_PROJECT_REQ: 'LOAD_SELECTED_PROJECT_REQ',
	LOAD_SELECTED_PROJECT_SUCCESS: 'LOAD_SELECTED_PROJECT_SUCCESS',
	LOAD_SELECTED_PROJECT_FAILURE: 'LOAD_SELECTED_PROJECT_FAILURE',

	LOAD_SELECTED_TASK_REQ: 'LOAD_SELECTED_TASK_REQ',
	LOAD_SELECTED_TASK_SUCCESS: 'LOAD_SELECTED_TASK_SUCCESS',
	LOAD_SELECTED_TASK_FAILURE: 'LOAD_SELECTED_TASK_FAILURE',

	UPDATE_PROJECT_REQ: 'UPDATE_PROJECT_REQ',
	UPDATE_PROJECT_SUCCESS: 'UPDATE_PROJECT_SUCCESS',
	UPDATE_PROJECT_FAILURE: 'UPDATE_PROJECT_FAILURE',

	ADD_MEMBERS_REQ: 'ADD_MEMBERS_REQ',
	ADD_MEMBERS_SUCCESS: 'ADD_MEMBERS_SUCCESS',
	ADD_MEMBERS_FAILURE: 'ADD_MEMBERS_FAILURE',

	LOAD_PROJECT_TIMELINE_REQ: 'LOAD_PROJECT_TIMELINE_REQ',
	LOAD_PROJECT_TIMELINE_SUCCESS: 'LOAD_PROJECT_TIMELINE_SUCCESS',
	LOAD_PROJECT_TIMELINE_FAILURE: 'LOAD_PROJECT_TIMELINE_FAILURE',

	REMOVE_MEMBER_REQ: 'REMOVE_MEMBER_REQ',
	REMOVE_MEMBER_SUCCESS: 'REMOVE_MEMBER_SUCCESS',
	REMOVE_MEMBER_FAILURE: 'REMOVE_MEMBER_FAILURE',

	CREATE_LABELS_REQ: 'CREATE_LABELS_REQ',
	CREATE_LABELS_SUCCESS: 'CREATE_LABELS_SUCCESS',
	CREATE_LABELS_FAILURE: 'CREATE_LABELS_FAILURE',

	DELETE_LABELS_REQ: 'DELETE_LABELS_REQ',
	DELETE_LABELS_SUCCESS: 'DELETE_LABELS_SUCCESS',
	DELETE_LABELS_FAILURE: 'DELETE_LABELS_FAILURE',

	UPDATE_LABELS_REQ: 'UPDATE_LABELS_REQ',
	UPDATE_LABELS_SUCCESS: 'UPDATE_LABELS_SUCCESS',
	UPDATE_LABELS_FAILURE: 'UPDATE_LABELS_FAILURE',

	UPDATE_PERMISSIONS_REQ: 'UPDATE_PERMISSIONS_REQ',
	UPDATE_PERMISSIONS_SUCCESS: 'UPDATE_PERMISSIONS_SUCCESS',
	UPDATE_PERMISSIONS_FAILURE: 'UPDATE_PERMISSIONS_FAILURE',

	NEW_TASK_REQ: 'NEW_TASK_REQ',
	NEW_TASK_SUCCESS: 'NEW_TASK_SUCCESS',
	NEW_TASK_FAILURE: 'NEW_TASK_FAILURE',

	EDIT_TASK_REQ: 'EDIT_TASK_REQ',
	EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
	EDIT_TASK_FAILURE: 'EDIT_TASK_FAILURE',
}

export default ACTIONS
