const ACTIONS = {
	LOAD_ALL_PROJECTS_REQ: 'LOAD_ALL_PROJECTS_REQ',
	LOAD_ALL_PROJECTS_SUCCESS: 'LOAD_ALL_PROJECTS_SUCCESS',
	LOAD_ALL_PROJECTS_FAILURE: 'LOAD_ALL_PROJECTS_FAILURE',

	LOAD_INPROGRESS_PROJECTS_REQ: 'LOAD_INPROGRESS_PROJECTS_REQ',
	LOAD_INPROGRESS_PROJECTS_SUCCESS: 'LOAD_INPROGRESS_PROJECTS_SUCCESS',
	LOAD_INPROGRESS_PROJECTS_FAILURE: 'LOAD_INPROGRESS_PROJECTS_FAILURE',

	LOAD_OVERDUE_PROJECTS_REQ: 'LOAD_OVERDUE_PROJECTS_REQ',
	LOAD_OVERDUE_PROJECTS_SUCCESS: 'LOAD_OVERDUE_PROJECTS_SUCCESS',
	LOAD_OVERDUE_PROJECTS_FAILURE: 'LOAD_OVERDUE_PROJECTS_FAILURE',

	LOAD_CLOSED_PROJECTS_REQ: 'LOAD_CLOSED_PROJECTS_REQ',
	LOAD_CLOSED_PROJECTS_SUCCESS: 'LOAD_CLOSED_PROJECTS_SUCCESS',
	LOAD_CLOSED_PROJECTS_FAILURE: 'LOAD_CLOSED_PROJECTS_FAILURE',
}

export default ACTIONS
