const initalState = {
	personalDetails: {
		department: '',
		dob: '',
		emailId: '',
		employeeStatus: '',
		firstName: '',
		gender: '',
		lastName: '',
		middleName: '',
		maritalStatus: '',
		phoneNumber: '',
		errors: {},
	},
	mailingAddress: {
		line1: '',
		line2: '',
		city: '',
		state: '',
		country: '',
		zip: '',
		errors: {},
	},
	emergencyContact: {
		name: '',
		phone: '',
		city: '',
		errors: {},
	},
	employmentHistory: {
		client: '',
		clientAddress: '',
		managerReferMail: '',
		vendorName: '',
		vendorPhone: '',
		vendorEmail: '',
		fromDate: '',
		toDate: '',
		experience: '',
		errors: {},
	},
	workAuth: {
		type: '',
		number: '',
		issueDate: '',
		expiryDate: '',
		docUrl: '',
		errors: {},
	},
	password: '',
	confirmPassword: '',
}

export default initalState
