const ACTIONS = {
	SIGN_IN_REQ: 'SIGN_IN_REQ',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

	SIGN_UP_REQ: 'SIGN_UP_REQ',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

	SIGN_OUT_REQ: 'SIGNOUT_REQUEST',
	SIGN_OUT_SUCCESS: 'SIGNOUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGNOUT_FAILURE',

	FORGOT_PASSWORD_REQ: 'FORGOT_PASSWORD_REQ',
	FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
	FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

	CHANGE_PASSWORD_REQ: 'CHANGE_PASSWORD_REQ',
	CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
	CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
}

export default ACTIONS
